spring:
  profiles:
    active: develop
  datasource:
    url: jdbc:mysql://192.168.99.100:3306/db_customer
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:db/changelog/liquibase-changelog.yaml

server:
  address: localhost
  port: 8080

customer:
  date-format: dd/MM/yyyy
  life-expectancy: 75
  min-value-statistics: 2
