spring:
  profiles:
    active: develop
  datasource:
    url: jdbc:mysql://b0611a74eabbf7:6ab582ae@us-cdbr-iron-east-03.cleardb.net/heroku_35f501fe85bbecb?reconnect=true/
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:db/changelog/liquibase-changelog.yaml

customer:
  date-format: dd/MM/yyyy
  life-expectancy: 75
  min-value-statistics: 2
